import logging

import pytest

from pages.expenses.create_vendor import Create_Vendor

logger = logging.getLogger(__name__)

@pytest.mark.needs_login
def test_ete_create_vendor(expense_setup, create_vendor_test_data):
    driver = expense_setup
    create_vendor = Create_Vendor(driver)
    logger.info("Test case started")
    create_vendor.create_vendor_mod_expense()
    logger.info("clicked on Expense module")
    create_vendor.create_vendor_submod_vendor()
    logger.info("clicked on Vendor sub-module")
    create_vendor.create_vendor_new_vendor()
    logger.info("clicked on Create Vendor button")
    create_vendor.create_vendor_title(create_vendor_test_data)
    logger.info("Title entered")
    create_vendor.create_vendor_firstname(create_vendor_test_data)
    logger.info("firstname entered")
    create_vendor.create_vendor_middlename(create_vendor_test_data)
    logger.info("middlename entered")
    create_vendor.create_vendor_lastname(create_vendor_test_data)
    logger.info("lastname entered")
    create_vendor.create_vendor_displayname(create_vendor_test_data)
    logger.info("display name entered")
    create_vendor.create_vendor_email(create_vendor_test_data)
    logger.info("email entered")
    create_vendor.create_vendor_phonenumber(create_vendor_test_data)
    logger.info("phone number entered")
    create_vendor.create_vendor_mobile_numcountry(create_vendor_test_data)
    logger.info("country selected for mobile number")
    create_vendor.create_vendor_mobile_number(create_vendor_test_data)
    logger.info("mobile number entered")
    create_vendor.create_vendor_gsttreatment(create_vendor_test_data)
    logger.info("selected gst treatment")
    create_vendor.create_vendor_gstnumber(create_vendor_test_data)
    logger.info("gst number entered")
    create_vendor.create_vendor_address(create_vendor_test_data)
    logger.info("address added")
    create_vendor.create_vendor_note(create_vendor_test_data)
    logger.info("note entered")
    create_vendor.create_vendor_creditterms(create_vendor_test_data)
    logger.info("credit terms selected ")
    create_vendor.create_vendor_saveandclose()
    logger.info("Test case Ended")

@pytest.mark.needs_login
def test_verify_create_vendor_successfully(expense_setup, create_vendor_test_data):
    driver = expense_setup
    create_vendor = Create_Vendor(driver)
    logger.info("Test case started")
    create_vendor.create_vendor_mod_expense()
    logger.info("clicked on Expense module")
    create_vendor.create_vendor_submod_vendor()
    logger.info("clicked on Vendor sub-module")
    create_vendor.create_vendor_new_vendor()
    logger.info("clicked on Create Vendor button")
    create_vendor.create_vendor_title(create_vendor_test_data)
    logger.info("Title entered")
    create_vendor.create_vendor_firstname(create_vendor_test_data)
    logger.info("firstname entered")
    create_vendor.create_vendor_middlename(create_vendor_test_data)
    logger.info("middlename entered")
    create_vendor.create_vendor_lastname(create_vendor_test_data)
    logger.info("lastname entered")
    create_vendor.create_vendor_displayname(create_vendor_test_data)
    logger.info("display name entered")
    create_vendor.create_vendor_email(create_vendor_test_data)
    logger.info("email entered")
    create_vendor.create_vendor_phonenumber(create_vendor_test_data)
    logger.info("phone number entered")
    create_vendor.create_vendor_mobile_numcountry(create_vendor_test_data)
    logger.info("country selected for mobile number")
    create_vendor.create_vendor_mobile_number(create_vendor_test_data)
    logger.info("mobile number entered")
    create_vendor.create_vendor_gsttreatment(create_vendor_test_data)
    logger.info("selected gst treatment")
    create_vendor.create_vendor_gstnumber(create_vendor_test_data)
    logger.info("gst number entered")
    create_vendor.create_vendor_address(create_vendor_test_data)
    logger.info("address added")
    create_vendor.create_vendor_note(create_vendor_test_data)
    logger.info("note entered")
    create_vendor.create_vendor_creditterms(create_vendor_test_data)
    logger.info("credit terms selected ")
    create_vendor.create_vendor_saveandclose()
    logger.info("Clicked on Save and close")
    create_vendor.create_vendor_saved_successfully(create_vendor_test_data)
    logger.info("Created vendor is searched on vendor list")
    logger.info("Test case Ended")
