name: Mocha_Accounting_suite

on:
  schedule:
    # Runs daily at 9:00 AM IST (03:30 UTC)
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run lint, tests, and push logs
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        set +e

        LOG_DIR=daily_login_crons
        LOG_FILE=$LOG_DIR/daily_login_crons_status_$(date -u +'%Y-%m-%d').log
        mkdir -p $LOG_DIR

        START_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")

        {
          echo "========== Linting Errors =========="
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "========== End of Linting =========="

          echo "============================================"
          echo "Test Run Started: $START_TIME"
          echo "--------------------------------------------"

          pytest tests/ -v
          TEST_EXIT_CODE=$?

          END_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")
          DURATION=$(($(date -d "$END_TIME" +%s) - $(date -d "$START_TIME" +%s)))
          STATUS=$([ $TEST_EXIT_CODE -eq 0 ] && echo "SUCCESS" || echo "FAILURE")

          echo "--------------------------------------------"
          echo "Test Run Finished: $END_TIME"
          echo "Duration: $DURATION seconds"
          echo "Status: $STATUS"
          echo "Exit Code: $TEST_EXIT_CODE"
          echo "============================================"
        } >> $LOG_FILE 2>&1

        echo "Test Summary: $STATUS"

        git config user.name "YashPayer2510"
        git config user.email "yash.payer@mochatechnologies.com"
        git add $LOG_FILE
        git commit -m "Daily test results - $END_TIME - Status: $STATUS"
        git push

        exit $TEST_EXIT_CODE
