name: Mocha_Accounting_suite

on:
  schedule:
    # Runs daily at 9:00 AM IST (03:30 UTC)
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libnss3 libxss1 libasound2t64 libxtst6 fonts-liberation

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html pytest-xdist webdriver-manager selenium python-dotenv beautifulsoup4 lxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Restore Gmail Token (for OTP retrieval)
      run: |
        mkdir -p utilities
        echo '${{ secrets.GMAIL_TOKEN }}' > utilities/token.json
        echo "token.json restored successfully"

    - name: Restore Gmail Credentials
      run: |
        mkdir -p utilities
        echo '${{ secrets.GMAIL_CREDENTIALS }}' > utilities/credentials.json
        echo "credentials.json restored successfully"

    - name: Run Login Tests
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        set +e
        LOG_DIR=daily_test_logs
        LOG_FILE=$LOG_DIR/login_tests_$(date -u +'%Y-%m-%d').log
        mkdir -p $LOG_DIR

        START_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")
        echo "=== LOGIN TESTS STARTED: $START_TIME ===" >> $LOG_FILE

        xvfb-run pytest tests/test_signup_login/test_login.py -v --tb=long -rP >> $LOG_FILE 2>&1
        TEST_EXIT_CODE=$?

        echo "=== LOGIN TESTS COMPLETED ===" >> $LOG_FILE
        echo "Exit Code: $TEST_EXIT_CODE" >> $LOG_FILE
        echo "=== Login Tests Summary ==="
        tail -10 $LOG_FILE
        exit $TEST_EXIT_CODE

    - name: Run Registration Tests
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        set +e
        LOG_DIR=daily_test_logs
        LOG_FILE=$LOG_DIR/registration_tests_$(date -u +'%Y-%m-%d').log
        mkdir -p $LOG_DIR

        START_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")
        echo "=== REGISTRATION TESTS STARTED: $START_TIME ===" >> $LOG_FILE

        xvfb-run pytest tests/test_signup_login/test_sign_up.py -v --tb=long -rP >> $LOG_FILE 2>&1
        TEST_EXIT_CODE=$?

        echo "=== REGISTRATION TESTS COMPLETED ===" >> $LOG_FILE
        echo "Exit Code: $TEST_EXIT_CODE" >> $LOG_FILE
        echo "=== Registration Tests Summary ==="
        tail -10 $LOG_FILE
        exit $TEST_EXIT_CODE

    - name: Commit and Push Test Results
      if: always()
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "YashPayer2510"
        git config user.email "yash.payer@mochatechnologies.com"

        if git status --porcelain | grep -q "daily_test_logs/"; then
          git add daily_test_logs/
          git commit -m "Daily test results - $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
          echo "Test logs committed successfully"
        else
          echo "No new test logs to commit"
        fi

    - name: Upload test logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: daily_test_logs/
        retention-days: 30
