# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Mocha_Accouting_suite

on:
  workflow_dispatch: 
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
         pytest tests/test_login.py
          LOG_DIR=cron_logs
          LOG_FILE=$LOG_DIR/cron_status.log

          mkdir -p $LOG_DIR

          echo "$(date -u) - LOGIN TEST SUCCESS" >> $LOG_FILE

          git config user.name "YashPayer2510"
          git config user.email "yash.payer@mochatechnologies.com"
          
          if [ -f "$LOG_FILE" ]; then
          git add $LOG_FILE
          git commit -m "Cron status logged on $(date -u)"
          git push https://${{ secrets.GH_PAT }}@github.com/YashPayer2510/Mocha_accounting.git main

          else
            echo "Log file not found: $LOG_FILE"
          fi
         
